############################
## HUGO MODULES - SIMPLIFIED
## Minimal configuration for stable deployment
############################

# No external module imports - use built-in Hugo functionality
# This eliminates complex dependencies and version conflicts
